TIDES-transit/TIDES

CONTRIBUTING.md
This is the rewrite of CONTRIBUTING.md (formerly in Google Doc).  Still need to complete the "creating good issues and pull requests" section.
=> New version of CONTRIBUTING.md

.github/ISSUE_TEMPLATE/code_bug.md, .github/ISSUE_TEMPLATE/code_feature.md, .github/ISSUE_TEMPLATE/spec_bug.md, .github/ISSUE_TEMPLATE/spec_feature.md
=> add code issue templates

index.html
This PR sets the default documentation site to reflect the documentation build in the `main` branch. 
Fixes #22
=> Set default documentation to main branch

.github/workflows/clean-docs.yml
=> add and cache docs/requirements.txt for clean-docs workflow

.pre-commit-config.yaml
=> fix pre-commit check-yaml

spec/vehicle_locations.schema.json
=> Make trip_id_performed optional in vehicle_locations

spec/fare_transactions.schema.json, spec/passenger_events.schema.json, spec/stop_visits.schema.json, spec/trips_performed.schema.json, spec/vehicle_locations.schema.json
Add pattern_id to any file with trip_id_performed.
Closes #90
=> add pattern_id

spec/fare_transactions.schema.json
=> Make currency_type optional in fare_transactions

.github/workflows/validate_table_schemas.yml, .github/workflows/validate_tables_noop.yml
Fixes the path spec in the table validation workflows to reference the actual table json files!
Closes #120
=> fix path spec for validation workflows

spec/stop_visits.schema.json
Clarify meaning of boarding and alighting fields in stop_visits
Resolves #113 .
=> Clarify meaning of boarding and alighting fields in stop_visits

spec/fare_transactions.schema.json
Remove fare_media_id_purchase as discussed in the linked issue.
Before submitting a pull request, please read [CONTRIBUTING.md](CONTRIBUTING.md).
For spec changes:
=> Remove fare_media_id_purchased from fare_transactions

spec/devices.schema.json, spec/fare_transactions.schema.json, spec/trips_performed.schema.json
=> 115 rename fields for clarity

.github/workflows/clean-docs.yml, .github/workflows/docs.yml
Work in progress - attempting to resolve docs build issues highlighted in #62, which would also encompass work to fix #60.
For spec changes:
=> Update GitHub Actions to Prevent PR Double Runs

.github/workflows/clean-docs.yml, .github/workflows/docs.yml
This PR resolves the error in #60 where Mike doesn't have the most up to date gh-pages branch on which to rebase.
Fixes #60 
Trying:
- Fetch GH Pages before mike --rebase
=> WIP: Fix Mike Rebase

spec/fare_transactions.schema.json, spec/passenger_events.schema.json, spec/vehicle_locations.schema.json
=> 70 trips performed summary table cant be summarized from event tables

samples/template/TIDES/train_cars.csv, samples/template/TIDES/vehicles.csv, spec/devices.schema.json, spec/fare_transactions.schema.json, spec/passenger_events.schema.json, spec/stop_visits.schema.json, spec/train_cars.schema.json, spec/vehicle_locations.schema.json, spec/vehicles.schema.json
Fixes #187
Bugs
* Added service_date to trips_performed foreign key in fare_transactions, passenger_events, stop_visits, vehicle_locations
* Changed train_car to train_cars in foreign key in passenger_events
* Pointed passenger_events.trip_stop_sequence in passenger_events to stop_visits.trip_stop_sequence in the stop_visits foreign key
* Removed foreign key to stop_times
Styles
* Modified enums for devices to start with an uppercase letter
* Changed all capacity columns to capacity_xxxx
=> Fix implementation challenges (#187)

README.md, docs/governance/meetings.md, mkdocs.yml
- add text from one-pager in readme.md which will also render to homepage
- also added minutes page for board meetings.
This is a non-normative change.
=> Add info from one-pager

docs/governance/actions/2023-12-06 designate-tides-board-coordinator.md, docs/governance/actions/2023-12-06 designate-tides-manager.md, docs/governance/policies/change-management.md
Google drive links changed to reference tides-transit-data account.
=> Updated google doc references

docs/awesome.md, docs/requirements.txt, mkdocs.yml
Add awesome-pages to be rendered in documentation.
---
=> 📄  [DOCS] Added awesome pages

docs/governance.md, docs/governance/meetings.md
Added overall link to rolling agendas/meeting as well as links to heading of previous and future mtgs.
=> 📄  [DOCS] Add Meeting Note Links

README.md, mkdocs.yml
=> Update acronym: ITS --> Integrated
