TIDES-transit/TIDES

.github/workflows/docs.yml
.github/workflows/validate_package_noop.yml
.github/workflows/validate_package_schema.yml
.github/workflows/validate_schemas.yml
.github/workflows/validate_table_schemas.yml
.github/workflows/validate_tables_noop.yml

- add token key to jsonschema validator action
- run validation only on pull-requests, works around <https://github.com/snapcart/json-schema-validator/issues/2>
- specify python-version for setup-python as '3.x' (latest stable) to use the `cache` feature, see <https://github.com/actions/setup-python/issues/475>
- use path constraints on validation workflows and split
- split table spec validation from data package validation to run the correct validation depending on the contents of the PR
- add `_noop` variants, so that validations succeed if no files match the path constraints (to allow PR merging), see <https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skip …

Fixes for workflows

---

docs/requirements.txt
mkdocs.yml

This Pull Request uses mkdocs-redirects to fix relative links for files that move from the main repo directory to the `/docs` directory. 
Closes #52

Fix redirects with files that moved into docs

---

docs/document.py
spec/devices.schema.json
spec/fare_transactions.schema.json
spec/operators.schema.json
spec/passenger_events.schema.json
spec/station_activities.schema.json
spec/stop_visits.schema.json
spec/train_cars.schema.json
spec/trips_performed.schema.json
spec/vehicle_locations.schema.json
spec/vehicle_train_cars.schema.json
spec/vehicles.schema.json

This does more than one thing, but they were all connected to improving documentation
- group spec tables by table type (Event, Summary, Supporting)
- sort tables alphabetically
- title case for table titles
- add table description
- add primary key
- add links to GTFS pages referenced
- add links for internal references (foreign IDs)
- add links for rdfTypes
additionally, to make these features function properly, i made the following changes to the spec:
- add a private `_table_type` property (Event, Summary or Supporting)
- fix typo in references to `train_car` to `train_cars`
- change a reference to GTFS trips_performed to an internal reference to the trips_performed table

documentation enhancement omnibus PR of 2022

---

CONTRIBUTING.md

This PR removes reference to Blake in the PMT membership since he has left the Cal-ITP project.

Update PMT Membership

---

spec/devices.schema.json
spec/fare_transactions.schema.json
spec/passenger_events.schema.json
spec/station_activities.schema.json
spec/stop_visits.schema.json
spec/trips_performed.schema.json
spec/vehicle_locations.schema.json
spec/vehicle_train_cars.schema.json

This pull request addresses part 2 of issue #77 by using `foreignKeys` instead of `foreignReferences` 
Using `foreignKeys` in  the spec creates a dependency to another file, which is not the intention. Instead, foreign keys were intended to document optional relationships between files. The existing behavior prevents sample datasets from validating. For example, when providing a `vehicle_locations` file, but not also including `devices` and `train_cars`.
- Change the behavior of the validator to change `foreignKeys` from enforced to informational.
- Add an `enforced` attribute to `foreignKeys` so the validator can determine when to enforce the relationship.
- **This PR:** Use a custom property, e.g., `foreignReferences`.
The first two options would require either changes to the existing …

fix unintended foreign key dependencies

---

spec/fare_transactions.schema.json
spec/passenger_events.schema.json
spec/stop_visits.schema.json
spec/trips_performed.schema.json
spec/vehicle_locations.schema.json
spec/vehicles.schema.json

This PR changes all `time` fields to `datetime`, and all instances of 'time' in the field description to 'timestamp'.
Use of `datetime` instead of `integer` keeps fields human readable and avoids some ambiguities around daylight savings time.
This PR does not rename fields, though that may also be desirable, e.g., `date` to `service_date`, or `timestamp` to `event_timestamp`.
Closes #31

Support >24 hour service clocks

---

spec/vehicle_locations.schema.json

Use `number` type to support sub-meter resolution
Closes #86

fix odometer type

---

spec/passenger_events.schema.json

Adds `count` to the passenger_events table.
I set the minimum to 0, but since the default is 1 and it's not clear what 0 would mean, it should probably be changed to 1.
Closes #73

add optional count field

---

spec/devices.schema.json
spec/fare_transactions.schema.json
spec/passenger_events.schema.json
spec/station_activities.schema.json
spec/stop_visits.schema.json
spec/trips_performed.schema.json
spec/vehicle_locations.schema.json
spec/vehicle_train_cars.schema.json

Updates several field names to avoid SQL keywords in common databases:
Schema | Current Field Name | Proposed Field Name
-- | -- | --
fare_transactions | date | service_date
fare_transactions | timestamp | event_timestamp
passenger_events | date | service_date
passenger_events | timestamp | event_timestamp
passenger_events | count | event_count
vehicle_locations | date | service_date
vehicle_locations | timestamp | event_timestamp
station_activities | date | service_date
stop_visits | date | service_date
stop_visits | checkpoint | timepoint
stop_visits | load | vehicle_load
trips_performed | date | service_date
devices | location | device_location
vehicle_train_cars | order | train_car_order
Closes #82

Fixed fields clashing with SQL keywords

---

spec/station_activities.schema.json
spec/stop_visits.schema.json
spec/trips_performed.schema.json

change `date` to `service_date` in primary field definitions.
Closes #117

fix primary key fields

---

.github/workflows/validate_package_noop.yml
.github/workflows/validate_package_schema.yml
.github/workflows/validate_table_schemas.yml
.github/workflows/validate_tables_noop.yml

GitHub does not support the grep '$' operator, so no validations have run on spec changes.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
This needs to merge before any other PRs can be merged, so that the appropriate checks can run.
Re #120

fix path specs in GitHub Actions validation workflows

---

mkdocs.yml

Pins mermaid to version 9.4.3, to avoid incompatibility between version 10 and mkdocs. 
There's an open issue to make version 10 work with mkdocs.
https://github.com/fralau/mkdocs-mermaid2-plugin/issues/70
There's a work-around in the above issue where you create a new javascript file that loads the ESM module of mermaid v10. I'm open to that as well.

Fix mermaid

---

.github/workflows/validate_table_schemas.yml

Should fix failing validations on pull-requests because schema was unavailable.
See table schema validation failure [here](https://github.com/TIDES-transit/TIDES/actions/runs/4833928906/jobs/8614537603#step:4:18)
Closes #133

Fix frictionless table schema url

---

docs/architecture.md
spec/fare_transactions.schema.json
spec/trips_performed.schema.json

This PR adds explicit description of the implied relationship between `trip_id` in GTFS and `trip_id_performed` if and when trips exist in both datasets.
Based on discussion for issue #50

Adds description about consistency of trip_ids

---

CONTRIBUTING.md
mkdocs.yml
requirements.txt

This PR adds documentation on how to manually validate schema files. 
Also 
- fix mkdocs to allow tabs
- add frictionless to requirements.
Fixes #146 

Add documentation on manually validating schema files

---

.github/workflows/docs.yml

Resolves #69 by returning the `github-script` Action to use on a version that resolves the errors the TIDES repo experienced with the previously used version (v5).

Fix PR comment GitHub Action

---

.github/workflows/validate_package_schema.yml
.github/workflows/validate_table_schemas.yml
spec/operators.schema.json
spec/table-schema.json
spec/tides-data-package.json
spec/tides.spec.json

This PR resolves #136 via a personal fork of the unmaintained GitHub Action we had in use - we can always fork a version directly under the TIDES project later instead of having it live under my GitHub account.
The PR also uses `tides-data-package` to validate `tides.spec.json`, and makes small changes to `tides.spec.json` in order to pass validation.
The merge-ready PR doesn't include a run of the second Action that was changed, defined in `validate_table_schemas.yml`, but that was tested on previous commits via small changes to `operators.schema.json` that have now been undone.

Fix JSON validator + correct tides.spec.json for successful validation

---

.github/workflows/docs.yml

When we merged #150, I noticed that the conditions used to generate the docs link comment on PRs were overly broad - the task tried to fire after merge with a then-incorrect URL, which is unnecessary and [causes a CI failure upon merge](https://github.com/TIDES-transit/TIDES/actions/runs/5524648268/jobs/10077228341) that doesn't reflect a "real" issue.
I've reformulated the `if` condition so that the comment action doesn't fire on a merge commit. [I tested this on a personal fork](https://github.com/SorenSpicknall/TIDES/pull/1) and confirmed that A.) the comment action works as expected during pull request events, and B.) it is skipped upon merge.

Don't run comment action on merge

---

CONTRIBUTING.md

This pull request adds documentation about how the documentation is defined in built to `CONTRIBUTING.md`
Closes #137 

Adds content on how documentation is built to CONTRIBUTING

---

.github/workflows/validate_samples.yml
spec/fare_transactions.schema.json
spec/passenger_events.schema.json
spec/vehicle_locations.schema.json

Partially resolves #131 .  This adds the foreign references that @jaygordon listed as examples, but I have not thoroughly reviewed the repo to find other missing references.  In the TIDES discussion from 2 weeks ago I believe we said that we might be fine saying that this is good enough for the 1.0 milestone, and that other missing references can be added if and when they are discovered.
A question for those more familiar with frictionless: am I following the correct format for a multi-column reference?
This commit works well if we assume that `trip_id_performed` is unique each day *and* that fare transactions from some service date can only correspond to stop visits from the same service date, which is true in most cases.  But there could be an agency that runs through the night, with …

131 specify foreign key relationships that already exist but arent listed explicitly

---

.github/workflows/docs.yml

Re-add the if clause, but allow for any non-pull_request trigger.
Closes #168
Before submitting a pull request, please read [CONTRIBUTING.md](CONTRIBUTING.md).
For spec changes:

allow build-docs if trigger is not pull_request

---

docs/requirements.txt

Breaking change in mike 2.0 doesn't allow rebase.
This is a quick fix to pin mike to <2.0 to resolve for now. 
This should be fixed in resolving bug report filed in #173

Temporarily pin mike to <2.0

---

CLA.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
contributors.md
docs/development.md
docs/governance.md
main.py
mkdocs.yml

Fixes issue #175
Also:
-  Splits out CLA
-  Adds all contributors listed in GitHub team to contributors.md
-  Reduces redundant sections between contributing.md and /development using a macro `include_file_sections`
-  Moves governance.md from docs/governance to docs/ so the link isn't governance/governance/index.html (ugly!)

Update CONTRIBUTING.md to refer to governance.

---

CONTRIBUTING.md
LICENSE-APACHE-2.0
LICENSE-CC-BY-4.0
LICENSES
main.py
mkdocs.yml
samples/template/TIDES/datapackage.json

Fixes #178 
- Add TIDES Board of Directors as owner and copyright holder in licenese
Fixes #179
- Add CC-BY-4.0 license and apply it to data, documentation, and spec
- Add documentation on dual licensing in LICENSES
- Add footer to documentation specifying CC-BY-4.0
- Update references

Add licensor add/change to CC-BY-4.0; document dual license

---

.github/CODEOWNERS

Adds TIDES Contributors as default CODEOWNERS and TIDES Board for `/spec` directory and all governance docs. 
Refs: 
- [The format and purpose of of the CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
- [TIDES Governance](https://tides-transit.github.io/TIDES/main/governance/)
Fixes #182 once branch protection rules added.

Add CODEOWNERS consistent with TIDES governance

---

CONTRIBUTING.md

Add instructions and flags for developing on local fork

---

.github/workflows/clean-docs.yml

Previous requirement didn't work and nothing was cleaned.
Fixes #210

Change requirement for cleaning to be from TIDES repo.

---

.github/workflows/clean-docs.yml

Changes the branch lineage referenced in `clean-docs.yml` so that older docs versions associated with a branch's deletion event are targeted correctly for deletion, rather than the docs associated with the head branch after that event has happened. This is a follow-up to #215.
The event trigger behavior and the resulting branch ref was tested on a private repo before creating this PR.

Fix up event ref for deletion of docs associated with deleted branch
